name: Deploy Application

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    env:
      APP_DIR: ~/tmob/tschool/web
      APP_NAME: tschool-web
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the latest tag
        id: get-tag
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Validate tag
        run: |
          if [ -z "${{ steps.get-tag.outputs.latest_tag }}" ]; then
            echo "No tag found. Exiting."
            exit 1
          fi

      - name: Print the latest tag
        run: echo "The latest tag is ${{ steps.get-tag.outputs.latest_tag }}"

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-

      - name: Deploy application
        run: |
          cd ${{ env.APP_DIR }} && \
          git fetch private tag ${{ steps.get-tag.outputs.latest_tag }} && \
          git checkout ${{ steps.get-tag.outputs.latest_tag }} && \
          yarn && \
          yarn prisma generate && \
          yarn build
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Restart application with sudo
        run: |
          sudo pm2 restart ${{ env.APP_NAME }}

      - name: Clean up
        run: |
          yarn cache clean
          rm -rf node_modules/.cache
