name: Automate Branch Creation

on:
  issues:
    types: [opened]

jobs:
  create_branch_and_pr:
    runs-on: self-hosted

    steps:
      - name: Set up Git
        run: |
          cd tmob/tschool/web
          git fetch origin main
          nvm use 20
          yarn
          yarn build
          pm2 restart tschool-web
