name: Automate Branch Creation

on:
  issues:
    types: [opened]

jobs:
  create_branch_and_pr:
    runs-on: self-hosted

    steps:
      - name: Set up Git
        run: |
          git clone https://github.com/dcalliari/github-actions-test-lab.git
